version: "3.8"

services:
  mongo1:
    image: mongo:4.2
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    ports:
      - 30001:30001
    volumes:
      - ./data/mongo-1:/data/db
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:4.2
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    ports:
      - 30002:30002
    volumes:
      - ./data/mongo-2:/data/db
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:4.2
    container_name: mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    ports:
      - 30003:30003
    volumes:
      - ./data/mongo-3:/data/db
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
